### ISSUE TITLE
Multiple Commands With One Push?

### ISSUE THREAD

**Issue by jct32** [mauer/xmidictrl#10]
I was wondering if it was possible (currently or in the future) to have multiple commands send with the push of one button. This could be useful for consolidating commands just as landing lights or fuel pumps.

**Comment by mauer** [comment]
Hi,

Many thanks for your question. It's indeed already possible to assign multiple commands to one midi event (https://mauer.github.io/xmidictrl/#/inbound_mapping?id=multi-map).

Just add several mappings for the same midi event :-)

Example:
```
mapping = [
    { ch = 11, cc = 25, type = "cmd", command = "A300/accept_master_caution" },
    { ch = 11, cc = 25, type = "cmd", command = "A300/accept_master_warning" }
]
```

**Comment by jct32** [comment]
Ah missed it in the docs. Thank you!
