### ISSUE TITLE
Please compile for Apple MacOS M1 native processor

### ISSUE THREAD

**Issue by devleaks** [mauer/xmidictrl#15]
Hello,
I use XP12 in native M1 mode on Apple computers. Could you please recompile your code to make mac.xpl libraries M1 compatible. (I suggest you make them "fat" for both arm64 and x86_64.)
Thank you.

**Comment by mauer** [comment]
Hi,

I'm working on an universal build for both arm64 and x86_64. Unfortunately, I'm still having some build problems.

**Comment by beely** [comment]
I'll echo this - now that an M1 native SASL is available, xmidictrl will be the last plugin piece I need before I can go fully native, which will be great...

**Comment by mauer** [comment]
Good morning,

I finally managed to upgrade the X-Plane SDK and activate the universal build. Unfortunately, I don't have macOS to test the new version.

The file size increased from 4880084 to 8924160. That looks promising :-)

Would you mind to test this version [XMidiCtrl_1.04.zip](https://github.com/mauer/xmidictrl/files/10554695/XMidiCtrl_1.04.zip)?

Thanks,
Marco

**Comment by devleaks** [comment]
Wilco. It's normal that the size doubled, "fat binaries" 😃 actually have twice the code, for x86 and arm M1.
Will test later today.

**Comment by beely** [comment]
This is a good week for Mac X-Planers! Marco - I just gave this a quick spin natively and it seems to work as expected - it runs, MIDI assignments work, popup windows display etc. It also continues to work running XP under Rosetta to, so looking good! Thanks for this - I'll give it a proper workout later.
