### ISSUE TITLE
`default_encoder_mode` mentioned in documentation but not implemented

### ISSUE THREAD

**Issue by pilsnerish** [mauer/xmidictrl#32]
See: https://github.com/mauer/xmidictrl/blob/92623fb1e3a8f51edd65d604f45bdc645964f13b/docs/device.md?plain=1#L28

**Comment by mauer** [comment]
Hi,

I just checked the source code and it is implemented. I cannot test right now, but will look into it soon.

**Comment by pilsnerish** [comment]
GitHub is lying to me I guess? https://github.com/search?q=repo%3Amauer%2Fxmidictrl%20default_encoder_mode&type=code

**Comment by mauer** [comment]
I see, the parameter was called **encoder_mode** instead of **default_encoder_mode**.

I fixed it. Many thanks for your report. It's highly appreciated!
